nelmio_api_doc:
    documentation:
        info:
            title: Pub Quiz API
            description: API for a multiplayer pub quiz game using Open Trivia Database
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        path_patterns:
            - ^/api(?!/doc)
